### ISSUE TITLE
Manually filter out languages

### ISSUE THREAD

**Issue by hedyhli** [hedyhli/gtrending#33]
Sometimes when specified a language for fetch_repos on of the language isn't what we want. It may be a problem with the github trending API itself, but we should manually loop through the repos ourselves and remove the repos that doesn't match the specified language.

**Comment by deepaks2112** [comment]
Hi @hedyhli!

I want to contribute to this issue. How can I do so?

Thanks.

**Comment by hedyhli** [comment]
sure, I've assigned you
