### ISSUE TITLE
Web scraping data from GitHub Trending page instead

### ISSUE THREAD

**Issue by franz101** [hedyhli/gtrending#61]
SSLError: HTTPSConnectionPool(host='gtrend.yapie.me', port=443): Max retries exceeded with url: /languages (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1007)')))

**Comment by hedyhli** [comment]
The API that gtrending depended on seems to have expired, I believe this is a good opportunity to go for scraping GitHub trending ourselves instead of relying on an external API...

**Comment by hedyhli** [comment]
@franz101 you still have this error right?

**Comment by franz101** [comment]
I think this error was due to a missing certificate. But I just started scraping on my own.

**Comment by hedyhli** [comment]
Hi, this issue has been fixed as gtrending now scrapes github trending and no longer uses the API (see [v0.5.0](https://pypi.org/project/gtrending/0.5.0/)), thanks!
